// Macro for defining a buffer with a single array
#define TYPED_ARRAY_BUFFER(LAYOUT, BINDING, NAME, TYPE) \
    layout (LAYOUT, binding = BINDING) buffer NAME##Buffer \
    { TYPE sData[]; } NAME

// Pre-defined types of single-array buffers with common types
#define FLOAT_ARRAY_BUFFER(LAYOUT, BINDING, NAME) TYPED_ARRAY_BUFFER(LAYOUT, BINDING, NAME, float)
#define VEC2_ARRAY_BUFFER(LAYOUT, BINDING, NAME) TYPED_ARRAY_BUFFER(LAYOUT, BINDING, NAME, vec2)
#define VEC3_ARRAY_BUFFER(LAYOUT, BINDING, NAME) TYPED_ARRAY_BUFFER(LAYOUT, BINDING, NAME, vec3)
#define VEC4_ARRAY_BUFFER(LAYOUT, BINDING, NAME) TYPED_ARRAY_BUFFER(LAYOUT, BINDING, NAME, vec4)

#define UINT_ARRAY_BUFFER(LAYOUT, BINDING, NAME) TYPED_ARRAY_BUFFER(LAYOUT, BINDING, NAME, uint)
#define UVEC2_ARRAY_BUFFER(LAYOUT, BINDING, NAME) TYPED_ARRAY_BUFFER(LAYOUT, BINDING, NAME, uvec2)
#define UVEC3_ARRAY_BUFFER(LAYOUT, BINDING, NAME) TYPED_ARRAY_BUFFER(LAYOUT, BINDING, NAME, uvec3)
#define UVEC4_ARRAY_BUFFER(LAYOUT, BINDING, NAME) TYPED_ARRAY_BUFFER(LAYOUT, BINDING, NAME, uvec4)